CREATE PROCEDURE [cbo].[MIF_RFMODULE@GET_LIST](
    @A_ADDRESS            VARCHAR(12),
    @A_VENDOR             VARCHAR(50),
    @A_MODEL              VARCHAR(50),
	@N_RETURN	       int	 	OUTPUT,
	@V_RETURN	       VARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
    select	T1.ADDRESS,
			T1.VENDOR,
			T1.MODEL,
			T1.IC_NO,
			T1.LOT_NO,
			T1.WORKER,
			T1.ADDRESS_START,
			T1.ADDRESS_END,
			T1.AW_WORK_DATE,
			T1.AW_SIGNATURE_VAL,
			T1.AW_WAFER_LOT_VAL,
			T1.AW_BIN_CODE,
			T1.AW_ERROR_CODE,
			T1.AW_TEST_RESULT,
			T1.RF_WORKER,
			T1.RF_WORK_DATE,
			T1.RF_CONFIG_VER,
			T1.RF_LOSS_VAL,
			T1.RF_EVMOFFSET_VAL,
			T1.RF_TESTITEM_VAL,
			T1.RF_BIN_CODE,
			T1.RF_ERROR_CODE,
			T1.RF_TEST_RESULT,
			T1.AC_WORKER,
			T1.AC_WORK_DATE,
			T1.AC_SIGNATURE_VAL,
			T1.AC_WAFER_LOT_VAL,
			T1.AC_BIN_CODE,
			T1.AC_ERROR_CODE,
			T1.AC_TEST_RESULT,
			T1.FACTORY_SHIPMENTS

    from EISPTXNRFM T1
END TRY
BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
